# Generated by Django 3.2 on 2021-04-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the product', max_length=55)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('return_product_quantity', models.PositiveIntegerField(default=0)),
                ('total_sales_product', models.PositiveIntegerField()),
                ('daily_total_income', models.PositiveIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
