# Generated by Django 3.2 on 2021-04-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsalesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
