# Generated by Django 3.2 on 2021-04-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsalesapp', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='daily_total_income',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='return_product_quantity',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='total_sales_product',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='productsale',
            name='amount_of_sale',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='carton_price_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='number_of_carton',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='number_of_piece',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='piece_price_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='return_carton',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='return_piece',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='total_product_sale',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
