# Generated by Django 3.2 on 2021-04-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsalesapp', '0003_auto_20210416_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='amount_of_sale',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
