# Generated by Django 3.2 on 2021-04-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsalesapp', '0005_auto_20210418_0411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
